# Generated by Django 2.2.1 on 2019-06-14 18:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(choices=[('NRB', 'Nairobi'), ('NKR', 'Nakuru'), ('KMG', 'Kakamega'), ('ELD', 'Eldoret'), ('KSM', 'Kisumu'), ('BNM', 'Bungoma')], max_length=100)),
                ('to', models.CharField(choices=[('NRB', 'Nairobi'), ('NKR', 'Nakuru'), ('KMG', 'Kakamega'), ('ELD', 'Eldoret'), ('KSM', 'Kisumu'), ('BNM', 'Bungoma')], max_length=100)),
                ('price', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('phone_no', models.PositiveIntegerField()),
                ('to', models.CharField(choices=[('NRB', 'Nairobi'), ('NKR', 'Nakuru'), ('KMG', 'Kakamega'), ('ELD', 'Eldoret'), ('KSM', 'Kisumu'), ('BNM', 'Bungoma')], max_length=100)),
                ('origin', models.CharField(choices=[('NRB', 'Nairobi'), ('NKR', 'Nakuru'), ('KMG', 'Kakamega'), ('ELD', 'Eldoret'), ('KSM', 'Kisumu'), ('BNM', 'Bungoma')], max_length=100)),
                ('date_of_departure', models.DateField()),
                ('time_of_departure', models.CharField(choices=[('4', '4am'), ('6', '6am'), ('8', '8am'), ('10', '10am'), ('12', '12 noon'), ('20', '8 pm')], max_length=20)),
                ('seat_no', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
            ],
        ),
    ]
